src/Entity/Recipe.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $people;

    /**
     * @ORM\Column(type="smallint")
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="smallint")
     */
    private $total_duration;

    /**
     * @ORM\Column(type="smallint")
     */
    private $prep_duration;

    /**
     * @ORM\Column(type="smallint")
     */
    private $baking_duration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="recipes")
     */
    private $tag;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="createdRecipes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="favoriteRecipes")
     */
    private $userFavorites;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RecipeProduct", mappedBy="recipe")
     */
    private $recipeProducts;

    public function __construct()
    {
        $this->tag = new ArrayCollection();
        $this->userFavorites = new ArrayCollection();
        $this->created_at = new DateTime();
        $this->updated_at = new DateTime();
        $this->recipeProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPeople(): ?int
    {
        return $this->people;
    }

    public function setPeople(int $people): self
    {
        $this->people = $people;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTotalDuration(): ?int
    {
        return $this->total_duration;
    }

    public function setTotalDuration(int $total_duration): self
    {
        $this->total_duration = $total_duration;

        return $this;
    }

    public function getPrepDuration(): ?int
    {
        return $this->prep_duration;
    }

    public function setPrepDuration(int $prep_duration): self
    {
        $this->prep_duration = $prep_duration;

        return $this;
    }

    public function getBakingDuration(): ?int
    {
        return $this->baking_duration;
    }

    public function setBakingDuration(int $baking_duration): self
    {
        $this->baking_duration = $baking_duration;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUserFavorites(): Collection
    {
        return $this->userFavorites;
    }

    public function addUserFavorite(User $userFavorite): self
    {
        if (!$this->userFavorites->contains($userFavorite)) {
            $this->userFavorites[] = $userFavorite;
        }

        return $this;
    }

    public function removeUserFavorite(User $userFavorite): self
    {
        if ($this->userFavorites->contains($userFavorite)) {
            $this->userFavorites->removeElement($userFavorite);
        }

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|RecipeProduct[]
     */
    public function getRecipeProducts(): Collection
    {
        return $this->recipeProducts;
    }

    public function addRecipeProduct(RecipeProduct $recipeProduct): self
    {
        if (!$this->recipeProducts->contains($recipeProduct)) {
            $this->recipeProducts[] = $recipeProduct;
            $recipeProduct->setRecipe($this);
        }

        return $this;
    }

    public function removeRecipeProduct(RecipeProduct $recipeProduct): self
    {
        if ($this->recipeProducts->contains($recipeProduct)) {
            $this->recipeProducts->removeElement($recipeProduct);
            // set the owning side to null (unless already changed)
            if ($recipeProduct->getRecipe() === $this) {
                $recipeProduct->setRecipe(null);
            }
        }

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use App\Entity\Recipe;
use App\Entity\Product;
use App\Entity\RecipeProduct;
use App\Utils\TypeConfigurator;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class RecipeType extends TypeConfigurator
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, $this->getConfiguration("Titre de la recette :", "Tapez ici le titre de votre nouvelle recette !"))
            ->add('people', IntegerType::class, $this->getConfiguration('Nombre de personnes :', 'Indiquer pour combien de personne(s) est cette recette'))
            ->add('level', IntegerType::class, $this->getConfiguration("Difficulté :", "Niveau de difficulté de votre recette ")) 
            ->add('image', UrlType::class, $this->getConfiguration("Image :", "Votre image de profil"))
            ->add('prep_duration', IntegerType::class, $this->getConfiguration("Temps de préparation :", "Nombre de minute(s)"))
            ->add('baking_duration', IntegerType::class, $this->getConfiguration("Temps de cuisson :", "Nombre de minute(s)"))
            // ->add('recipe_products', EntityType::class, [
            //     'label' => 'Ajouter les ingrédients :',
            //     'class' => Product::class,
            //     'choice_label' => 'name',
            //     'multiple' => true,
            //     'expanded' => true,
            // ])
            ->add('content', TextType::class, $this->getConfiguration("Détail de la recette :", "Listez les instructions de votre recette "))
            ->add('tag', EntityType::class, [
                'label' => 'Choisir un tag :',
                'class' => Tag::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use Cocur\Slugify\Slugify;
use App\Repository\TagRepository;
use App\Repository\UserRepository;
use App\Repository\RecipeRepository;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Tag;

/**
 * @Route("/application/recettes", name="app_recipe_")
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(RecipeRepository $recipeRepo, TagRepository $tagRepo)
    {
        $recipes = $recipeRepo->findAll();

        $tags = $tagRepo->findAll();

        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipes,
            'tags' => $tags

        ]);
    }

    /**
     * @Route("/new", name="new")
     */
    public function create(Request $request)
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $slugger = new Slugify();

            $slug = $slugger->slugify($recipe->getName());

            $recipe->setSlug($slug);

            $recipe->SetTotalDuration($recipe->getPrepDuration() + $recipe->getBakingDuration());

            $recipe->setUser($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Votre recette est bien ajoutée'
            );

            return $this->redirectToRoute('app_recipe_ingredient_add', ['id' => $recipe->getId()]);
        }


        return $this->render('recipe/new.html.twig', [
            'form' => $form->createView()
                    ]);
    }

    /**
     * @Route("/{id}/ajouter-aux-favoris", name="add_fav")
     */
    public function addFav(Recipe $recipe)
    {
        $user = $this->getUser();
        $user->addFavoriteRecipe($recipe);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();

        $this->addFlash(
            'success',
            'Votre recette est bien ajoutée à vos favoris'
        );

        return $this->redirectToRoute('app_recipe_show', ['slug' => $recipe->getSlug()]);
    }

    /**
     * @Route("/{id}/supprimer-des-favoris", name="delete_fav")
     */
    public function deleteFav(Recipe $recipe)
    {
        $user = $this->getUser();
        $user->removeFavoriteRecipe($recipe);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();

        $this->addFlash(
            'success',
            'Votre recette est bien ajoutée à vos favoris'
        );

        return $this->redirectToRoute('app_user_recipe');
    }

    /**
     * @Route("/tag/{id}", name="tag")
     */
    public function tag(TagRepository $repo, $id)
    { 
        $tag = $repo->findOneById($id);

        return $this->render('recipe/tag.html.twig', [
            'tags' => $tag
            ]);
    }

    /**
     * @Route("/{slug}", name="show")
     */
    public function show(Recipe $recipe)
    {
        // Pas très opti car on génére une requête qui appel toutes les recettes favorites de l'utilisateur avant de les trier, l'idéale serait de le faire directement dans la requête. Mais pas dérangeant sur cette méthode en supposant que l'utilisateur n'aura pas 1000 recettes favorites
        $isFav = false;
        if ($this->getUser()->getFavoriteRecipes()->contains($recipe)) {
            $isFav = true;
        }

        $recipeProducts = $recipe->getRecipeProducts();

        // dd($recipeProducts);

        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
            'isFav' => $isFav,
            'recipeProducts' => $recipeProducts
                    ]);
    }
}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Recettes {% endblock %}
{% block stylesheets %} <link rel="stylesheet" href="{{ asset('assets/css/recipe.css') }}">{% endblock %}

{% block body %}
<div class="container">
    <h1>Toutes les recettes</h1>
    <div class="row">
    <aside class="col-2">
        {% for tag in tags %}
            <a href="{{path('app_recipe_tag', {'id':tag.id})}}"><span class="badge badge-info">{{ tag.name }}</span></a> </br>
        {% endfor %}
    </aside>
    <section class="col-10">
        <article class="row">
        {% for recipe in recipes %}

        <div class="col-3 mb-3 ">
            
            <div class="card" >
                <a href="{{ path('app_recipe_show', {'slug':recipe.slug}) }}">
                    <img src="{{recipe.image }}"  class="card-img-top" alt="">
                </a>
                <div class="card-body">
                    <h5 class="font-weight-bold">{{recipe.name}}</h5>
                    <p class="card-text"> Difficulté :
                        {% for i in 1..recipe.level %}
                            <i class="fas fa-utensil-spoon"></i>
                        {% endfor %}
                    </p>
                    <p class="card-text"> Personnes :
                        {% for i in 1..recipe.people %}
                            <i class="fas fa-utensil-spoon"></i>
                        {% endfor %}
                    </p>
                    {# Affichage des tags #}
                    <p>
                    {% for tag in recipe.tag %}
                    <a href="{{path('app_recipe_tag', {'id':tag.id})}}"><span class="badge badge-info">{{ tag.name }}</span></a>
                    {% endfor %}
                    </p>
                </div>
            </div>
            
        </div>
        

        {% endfor %}
        </article>
    </section>
    </div>
<a href="{{ path('app_recipe_new') }}" class="btn btn-success">Ajouter une recette</a>

</div>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | recettes {% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Creer une nouvelle recette</h1>

    {{form_start(form)}}
    {{form_widget(form)}}
    <button type="submit" class="btn btn-primary bg-dark">Ajouter des ingrédients</button>
    {{form_end(form)}}
    
</div>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | {{ recipe.name }} {% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('assets/css/recipe.css') }}">{% endblock %}

{% block body %}
<article class="container">
    <h1>{{ recipe.name }}</h1>
    {# Affichage des tags#}
    {% for tag in recipe.tag %}
    <a href="{{path('app_recipe_tag', {'id':tag.id})}}"><span class="badge badge-info">{{ tag.name }}</span></a>
    {% endfor %}

    {# A transformer en étoile du style github -> star ou unstar #}
    {% if isFav %}
    <a href="{{ path('app_recipe_delete_fav', {'id': recipe.id}) }}" class="btn btn-success mt-2">Supprimer des favorits</a>
    {% else %}
    <a href="{{ path('app_recipe_add_fav', {'id': recipe.id}) }}" class="btn btn-success">Ajouter à mes recettes favorites</a>
    {% endif %}


    <div class="row">
        <section class='col'>
            <p class="card-text"> Personnes :
                {% for i in 1..recipe.people %}
                    <i class="fas fa-utensil-spoon"></i>
                {% endfor %}
            </p>
            <p>Difficulté : 
                {# ajout de cuillere dans un 'for' on recuperer la difficulté qui est un chiffre, et chaque fois que l'on rentre dans le for on rajoute une cuillere, exemple si la difficulté est de 5, on boucle 5 fois et chaque fois que l'on boucle on ajoute une cuillere, cad qu'il aurait 5 cuilleres #}
                {% for i in 1..recipe.level %}
                    <i class="fas fa-utensil-spoon"></i>
                {% endfor %}
            </p>
            <p>temps total : {{ recipe.totalDuration }} minutes</p>
            <p>temps de préparation : {{ recipe.prepDuration }} minutes</p>
            <p>temps de cuisson : {{ recipe.bakingDuration }} minutes</p>
            <p><img src="{{ recipe.image }}" alt="Image de la recette {{ recipe.name }}"></p>
            <p>dernière modification : {{ recipe.updatedAt|date("d/m/Y") }}</p>
            <div>
                <p>Liste des ingrédients :</p>
                <ul>
                {% for product in recipeProducts %}
                    <li>{{ product.product }} - {{ product.quantity }} {{ product.product.measure}}(s)</li>
                {% endfor %}
                </ul>
            </div>
            <p>{{ recipe.content }}</p>
        </section>

    </div>
    <a href="#" class="btn btn-success">J'ai réalisé cette recette (enlever les ingrédients correspondant de mon
        Frigo)</a>

</article>
{% endblock %}

templates/recipe/tag.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | recettes {% endblock %}

{% block body %}
<article class="container">

    {# Affichage des tags#}
    <h1>{{ tags.name }}</h1>

    <div class="container">

        <div class="row">
            {% for recipe in tags.recipes %}
            <div class="col-3 mb-3 ">

                <div class="card">
                    <a href="{{ path('app_recipe_show', {'slug':recipe.slug}) }}">
                        <img src="{{recipe.image }}" class="card-img-top" alt="">
                    </a>
                    <div class="card-body">
                        <h5 class="font-weight-bold">{{recipe.name}}</h5>
                        <p class="card-text"> Difficulté :
                            {% for i in 1..recipe.level %}
                            <i class="fas fa-utensil-spoon"></i>
                            {% endfor %}
                        </p>
                        <p class="card-text"> Personnes :
                            {% for i in 1..recipe.people %}
                            <i class="fas fa-utensil-spoon"></i>
                            {% endfor %}
                        </p>
                        {# Affichage des tags #}
                        <p>
                            {% for tag in recipe.tag %}
                            <a href="{{path('app_recipe_tag', {'id':tag.id})}}"><span class="badge badge-info">{{ tag.name }}</span></a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</article>
{% endblock %}